name: Build Executables with PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Windows Build Job
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      # Retrieve Python version on Windows and set it as an environment variable
      - name: Retrieve Python Version on Windows
        id: get_python_version
        run: |
          # In PowerShell, use python --version and set environment variable
          $python_version = & python --version
          Write-Host "Python Version: $python_version"
          $env:PYTHON_VERSION = $python_version.Split(' ')[1]
          Write-Host "Setting PYTHON_VERSION=$($env:PYTHON_VERSION)"
          echo "PYTHON_VERSION=$($env:PYTHON_VERSION)" >> $env:GITHUB_ENV

      # Find pip cache directory dynamically on Windows
      - name: Get pip cache directory
        id: get_pip_cache_dir
        run: |
          $pip_cache_dir = & python -m pip cache dir
          echo "Pip cache directory is: $pip_cache_dir"
          echo "PIP_CACHE_DIR=$pip_cache_dir" >> $env:GITHUB_ENV

      # Cache pip dependencies for Windows
      - name: Cache Python dependencies (Windows)
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install pyinstaller

      # Build Executable using PyInstaller for Windows
      - name: Build Executable using PyInstaller for Windows
        run: |
          pyinstaller --onefile --console --name plexsyncer-${{ env.PYTHON_VERSION }}-win --distpath dist --workpath build --specpath spec cli.py  # Windows build

      - name: Upload Windows Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plexsyncer-executable-${{ github.run_id }}-${{ env.PYTHON_VERSION }}-windows
          path: dist/plexsyncer*

  # Linux and macOS Build Job
  linux-macos-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Cache pip dependencies for Linux/macOS
      - name: Cache Python dependencies (Linux/macOS)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install pyinstaller

      - name: Build Executable using PyInstaller for ${{ runner.os }}
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            pyinstaller --onefile --console --name plexsyncer-${{ matrix.python-version }}-linux --distpath dist --workpath build --specpath spec cli.py  # Linux build
          elif [ "${{ runner.os }}" == "macOS" ]; then
            pyinstaller --onefile --console --name plexsyncer-${{ matrix.python-version }}-macos --distpath dist --workpath build --specpath spec cli.py  # macOS build
          fi

      - name: Upload ${{ runner.os }} Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plexsyncer-executable-${{ github.run_id }}-${{ matrix.python-version }}-${{ runner.os }}
          path: dist/plexsyncer*
