name: Release Executable

on:
  push:
    branches:
      - main
    tags:
      - "v*" # Trigger on version tags
  pull_request:
    branches:
      - main

permissions:
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance

jobs:
  # Windows Build Job
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Retrieve Python Version on Windows
        id: get_python_version
        run: |
          $python_version = & python --version
          Write-Host "Python Version: $python_version"
          $env:PYTHON_VERSION = $python_version.Split(' ')[1]
          Write-Host "Setting PYTHON_VERSION=$($env:PYTHON_VERSION)"
          echo "PYTHON_VERSION=$($env:PYTHON_VERSION)" >> $env:GITHUB_ENV

      - name: Get pip cache directory
        id: get_pip_cache_dir
        run: |
          $pip_cache_dir = & python -m pip cache dir
          echo "Pip cache directory is: $pip_cache_dir"
          echo "PIP_CACHE_DIR=$pip_cache_dir" >> $env:GITHUB_ENV

      - name: Cache Python dependencies (Windows)
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir ${{ env.PIP_CACHE_DIR }} -r dev-requirements.txt
          pip install pyinstaller

      - name: Build Executable using PyInstaller for Windows
        run: |
          pyinstaller --onefile --console --name plexsyncer-${{ env.PYTHON_VERSION }}-win --distpath dist --workpath build --specpath spec cli.py

      - name: Upload Windows Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plexsyncer-executable-windows
          path: dist/plexsyncer*

  # Linux and macOS Build Job
  linux-macos-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.x]
    runs-on: ${{ matrix.os }}

    env:
      PIP_CACHE_DIR: ~/.cache/pip

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Retrieve Python Version on Linux/macOS
        id: get_python_version
        run: |
          python_version=$(python --version)
          echo "Python Version: $python_version"
          PYTHON_VERSION=$(echo $python_version | cut -d' ' -f2)
          echo "Setting PYTHON_VERSION=$PYTHON_VERSION"
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Cache Python dependencies (Linux/macOS)
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --cache-dir ${{ env.PIP_CACHE_DIR }} -r dev-requirements.txt
          pip install pyinstaller

      - name: Build Executable using PyInstaller for ${{ runner.os }}
        run: |
          if [ "${{ runner.os }}" == "Linux" ]; then
            pyinstaller --onefile --console --name plexsyncer-${{ env.PYTHON_VERSION }}-linux --distpath dist --workpath build --specpath spec cli.py
          elif [ "${{ runner.os }}" == "macOS" ]; then
            pyinstaller --onefile --console --name plexsyncer-${{ env.PYTHON_VERSION }}-macos --distpath dist --workpath build --specpath spec cli.py
          fi

      - name: Upload ${{ runner.os }} Executable as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plexsyncer-executable-${{ runner.os }}
          path: dist/plexsyncer*

  # Release Job
  release:
    needs: [windows-build, linux-macos-build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm ci

      - name: Download Windows Executable Artifact
        uses: actions/download-artifact@v4
        with:
          name: plexsyncer-executable-windows
          path: ./dist

      - name: Download Linux Executable Artifact
        uses: actions/download-artifact@v4
        with:
          name: plexsyncer-executable-Linux
          path: ./dist

      - name: Download macOS Executable Artifact
        uses: actions/download-artifact@v4
        with:
          name: plexsyncer-executable-macOS
          path: ./dist

      - name: Unpack Artifacts
        run: |
          mkdir -p binaries
          mv ./dist/plexsyncer* binaries/

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
